version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
       # to put env here if needed
       - aws s3 cp s3://$ENVIRONMENT_BUCKET/skynet-web/variables variables
       - source ./variables
       - npm install && npm run build
       - cp ./dist/main.bundle.js ./dist/main-$VERSION.bundle.js
artifacts:
  files:
    - '**/*'
  base-directory: dist
