version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
       - aws s3 cp s3://$ENVIRONMENT_BUCKET/zeus-web/.env .env
       - npm install && npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
